#include <stdint.h>
#include <stdio.h>

#include "actuator_protocol.h"

static int test_unpack_command_ok(void) {
    /* Vector generated from sim/actuator_codec.py */
    const uint8_t frame[ACTUATOR_CMD_FRAME_LEN] = {
        0x01, 0x03, 0x00, 0x03, 0x4d, 0x00, 0x00, 0x00,
        0xc4, 0x09, 0xdc, 0x05, 0x20, 0x03, 0x6f, 0x91,
        0x75, 0xe2
    };
    actuator_command_t cmd;

    if (actuator_unpack_command(frame, &cmd) == 0U) {
        return 0;
    }
    if (cmd.protocol_version != 1U || cmd.actuator_id != 3U || cmd.control_mode != 0U) {
        return 0;
    }
    if (cmd.sequence != 77U || cmd.target_position_norm_x10000 != 2500) {
        return 0;
    }
    if (cmd.target_rate_norm_per_s_x1000 != 1500U || cmd.max_effort_norm_x1000 != 800U) {
        return 0;
    }
    return 1;
}

static int test_unpack_feedback_ok(void) {
    /* Vector generated from sim/actuator_codec.py */
    const uint8_t frame[ACTUATOR_FB_FRAME_LEN] = {
        0x01, 0x03, 0x00, 0x00, 0x4d, 0x00, 0x00, 0x00,
        0x60, 0x09, 0x78, 0x05, 0xfa, 0x00, 0xc4, 0x01,
        0xe6, 0x0a, 0x46, 0x26, 0x4c, 0xd9
    };
    actuator_feedback_t fb;

    if (actuator_unpack_feedback(frame, &fb) == 0U) {
        return 0;
    }
    if (fb.protocol_version != 1U || fb.actuator_id != 3U || fb.feedback_mode != 0U) {
        return 0;
    }
    if (fb.sequence_echo != 77U || fb.measured_position_norm_x10000 != 2400) {
        return 0;
    }
    if (fb.measured_rate_norm_per_s_x1000 != 1400 || fb.motor_current_a_x100 != 250U) {
        return 0;
    }
    if (fb.temperature_c_x10 != 452 || fb.supply_voltage_v_x100 != 2790U) {
        return 0;
    }
    return 1;
}

static int test_crc_reject(void) {
    uint8_t frame[ACTUATOR_CMD_FRAME_LEN] = {
        0x01, 0x03, 0x00, 0x03, 0x4d, 0x00, 0x00, 0x00,
        0xc4, 0x09, 0xdc, 0x05, 0x20, 0x03, 0x6f, 0x91,
        0x75, 0xe2
    };
    actuator_command_t cmd;

    frame[2] ^= 0x01U;
    if (actuator_unpack_command(frame, &cmd) != 0U) {
        return 0;
    }
    return 1;
}

/*
 * Fault evaluation tests.
 * Vector actuator_id=5, sequence_echo=200, measured_position=0.30 (x10000=3000).
 * expected_position_x10000=3000, position_error_limit=ACTUATOR_POS_ERROR_LIMIT_X10000=2000.
 *
 * For position_mismatch test only: expected_position_x10000=0 so arithmetic
 * error = 3000 > 2000.
 */

static int test_evaluate_overtemperature(void) {
    /* fault_flags=0x02, temp_c_x10=1024 (102.4 C) — generated by sim/examples/generate_fault_vectors.py */
    const uint8_t frame[ACTUATOR_FB_FRAME_LEN] = {
        0x01, 0x05, 0x00, 0x02, 0xc8, 0x00, 0x00, 0x00,
        0xb8, 0x0b, 0xf4, 0x01, 0x2c, 0x01, 0x00, 0x04,
        0xbe, 0x0a, 0x89, 0x48, 0x44, 0x37
    };
    actuator_feedback_t fb;
    actuator_degrade_reason_t reason;

    if (actuator_unpack_feedback(frame, &fb) == 0U) {
        return 0;
    }
    /* Sanity-check decoded fault_flags and temperature */
    if (fb.fault_flags != 0x02U || fb.temperature_c_x10 != 1024) {
        return 0;
    }
    reason = actuator_evaluate_feedback(&fb, 3000, ACTUATOR_POS_ERROR_LIMIT_X10000);
    if (reason != ACTUATOR_DEGRADE_OVERTEMPERATURE) {
        return 0;
    }
    return 1;
}

static int test_evaluate_position_mismatch(void) {
    /* fault_flags=0x04, temp_c_x10=450 (45.0 C) — generated by sim/examples/generate_fault_vectors.py */
    const uint8_t frame[ACTUATOR_FB_FRAME_LEN] = {
        0x01, 0x05, 0x00, 0x04, 0xc8, 0x00, 0x00, 0x00,
        0xb8, 0x0b, 0xf4, 0x01, 0x2c, 0x01, 0xc2, 0x01,
        0xbe, 0x0a, 0x1d, 0x78, 0x31, 0xcf
    };
    actuator_feedback_t fb;
    actuator_degrade_reason_t reason;

    if (actuator_unpack_feedback(frame, &fb) == 0U) {
        return 0;
    }
    if (fb.fault_flags != 0x04U) {
        return 0;
    }
    /*
     * Pass expected_position=0 so arithmetic error = |3000 - 0| = 3000 > 2000.
     * Both the arithmetic path and the fault-bit path fire; both contribute to
     * the same reason code POSITION_MISMATCH, so fault_count stays at 1.
     */
    reason = actuator_evaluate_feedback(&fb, 0, ACTUATOR_POS_ERROR_LIMIT_X10000);
    if (reason != ACTUATOR_DEGRADE_POSITION_MISMATCH) {
        return 0;
    }
    return 1;
}

static int test_evaluate_comm_timeout(void) {
    /* fault_flags=0x08, temp_c_x10=450 — generated by sim/examples/generate_fault_vectors.py */
    const uint8_t frame[ACTUATOR_FB_FRAME_LEN] = {
        0x01, 0x05, 0x00, 0x08, 0xc8, 0x00, 0x00, 0x00,
        0xb8, 0x0b, 0xf4, 0x01, 0x2c, 0x01, 0xc2, 0x01,
        0xbe, 0x0a, 0xf9, 0xd1, 0xc4, 0x8a
    };
    actuator_feedback_t fb;
    actuator_degrade_reason_t reason;

    if (actuator_unpack_feedback(frame, &fb) == 0U) {
        return 0;
    }
    if (fb.fault_flags != 0x08U) {
        return 0;
    }
    reason = actuator_evaluate_feedback(&fb, 3000, ACTUATOR_POS_ERROR_LIMIT_X10000);
    if (reason != ACTUATOR_DEGRADE_COMM_TIMEOUT) {
        return 0;
    }
    return 1;
}

static int test_evaluate_multi_fault(void) {
    /*
     * Construct a feedback struct directly (no frame needed) with both
     * overtemperature (bit + threshold) and comm_timeout bits set.
     */
    actuator_feedback_t fb;
    actuator_degrade_reason_t reason;

    fb.protocol_version = 1U;
    fb.actuator_id = 5U;
    fb.feedback_mode = 0U;
    fb.fault_flags = ACTUATOR_FAULT_OVERTEMPERATURE | ACTUATOR_FAULT_COMM_TIMEOUT;
    fb.sequence_echo = 200U;
    fb.measured_position_norm_x10000 = 3000;
    fb.measured_rate_norm_per_s_x1000 = 500;
    fb.motor_current_a_x100 = 300U;
    fb.temperature_c_x10 = 1024; /* 102.4 C > ACTUATOR_TEMP_LIMIT_X10 */
    fb.supply_voltage_v_x100 = 2750U;

    reason = actuator_evaluate_feedback(&fb, 3000, ACTUATOR_POS_ERROR_LIMIT_X10000);
    if (reason != ACTUATOR_DEGRADE_MULTI_FAULT) {
        return 0;
    }
    return 1;
}

int main(void) {
    if (!test_unpack_command_ok()) {
        printf("test_unpack_command_ok FAILED\n");
        return 1;
    }
    if (!test_unpack_feedback_ok()) {
        printf("test_unpack_feedback_ok FAILED\n");
        return 1;
    }
    if (!test_crc_reject()) {
        printf("test_crc_reject FAILED\n");
        return 1;
    }
    if (!test_evaluate_overtemperature()) {
        printf("test_evaluate_overtemperature FAILED\n");
        return 1;
    }
    if (!test_evaluate_position_mismatch()) {
        printf("test_evaluate_position_mismatch FAILED\n");
        return 1;
    }
    if (!test_evaluate_comm_timeout()) {
        printf("test_evaluate_comm_timeout FAILED\n");
        return 1;
    }
    if (!test_evaluate_multi_fault()) {
        printf("test_evaluate_multi_fault FAILED\n");
        return 1;
    }

    printf("actuator protocol tests passed\n");
    return 0;
}
